// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import * as dotenvExpand from 'dotenv-expand';
import { defineConfig } from 'prisma/config';

dotenvExpand.expand(dotenv.config());

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
