/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type PropertyImageDto = {
  /**
   * @example clx1234abcd
   */
  id: string;
  /**
   * @example https://picsum.photos/seed/maharajgunj1/800/600
   */
  url: string;
};

export type ListingItemDto = {
  /**
   * @example clx1234abcd
   */
  id: string;
  /**
   * @example Luxury Villa in Maharajgunj
   */
  title: string;
  /**
   * @example 45000000
   */
  price: number;
  /**
   * @example 5
   */
  beds: number;
  /**
   * @example 4
   */
  baths: number;
  /**
   * @example Maharajgunj
   */
  suburb: string;
  /**
   * @example house
   */
  propertyType: "house" | "apartment" | "townhouse" | "land" | "commercial";
  images: PropertyImageDto[];
  /**
   * @example Internal notes
   */
  internalNotes?: string;
};

export type ListingMetaDto = {
  /**
   * @example 42
   */
  total: number;
};

export type ListingsResponseDto = {
  data: ListingItemDto[];
  meta: ListingMetaDto;
};

export type ListingSingleItemDto = {
  /**
   * @example clx1234abcd
   */
  id: string;
  /**
   * @example Luxury Villa in Maharajgunj
   */
  title: string;
  /**
   * @example 45000000
   */
  price: number;
  /**
   * @example 5
   */
  beds: number;
  /**
   * @example 4
   */
  baths: number;
  /**
   * @example Maharajgunj
   */
  suburb: string;
  /**
   * @example house
   */
  propertyType: "house" | "apartment" | "townhouse" | "land" | "commercial";
  images: PropertyImageDto[];
  /**
   * @example Internal notes
   */
  internalNotes?: string;
  /**
   * Description of the property
   *
   * @example A beautiful house with 3 bedrooms and 2 bathrooms
   */
  description: string;
};

export type ListingGetResponseDto = {
  /**
   * The property listing
   */
  data: ListingSingleItemDto;
};
