/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  queryKeyFn,
  type RealEstateApiContext,
  useRealEstateApiContext,
} from "./realEstateApiContext";
import type * as Fetcher from "./realEstateApiFetcher";
import { realEstateApiFetch } from "./realEstateApiFetcher";
import type * as Schemas from "./realEstateApiSchemas";
import { deepMerge } from "./realEstateApiUtils";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type AppControllerGetListingsQueryParams = {
  /**
   * Number of records to skip for pagination
   *
   * @example 0
   */
  skip?: number;
  /**
   * Number of records to return
   *
   * @example 10
   */
  limit?: number;
  /**
   * Search across title, description, and suburb
   *
   * @example villa
   */
  searchTerm?: string;
  /**
   * Field to sort results by
   */
  sortBy?: "createdAt" | "price" | "beds" | "baths";
  /**
   * Sort direction
   */
  sortOrder?: "asc" | "desc";
  /**
   * Filter by exact number of bedrooms
   *
   * @example 3
   */
  beds?: number;
  /**
   * Filter by exact number of bathrooms
   *
   * @example 2
   */
  baths?: number;
  /**
   * Minimum price in NPR
   *
   * @example 5000000
   */
  minPrice?: number;
  /**
   * Maximum price in NPR
   *
   * @example 50000000
   */
  maxPrice?: number;
  /**
   * Filter by admin status
   *
   * @example false
   */
  isAdmin?: boolean;
  /**
   * Filter by property type
   */
  propertyType?: "house" | "apartment" | "townhouse" | "land" | "commercial";
};

export type AppControllerGetListingsError = Fetcher.ErrorWrapper<undefined>;

export type AppControllerGetListingsVariables = {
  queryParams?: AppControllerGetListingsQueryParams;
} & RealEstateApiContext["fetcherOptions"];

/**
 * Returns paginated property listings with optional filters for search term, price range, property type, beds, and baths.
 */
export const fetchAppControllerGetListings = (
  variables: AppControllerGetListingsVariables,
  signal?: AbortSignal,
) =>
  realEstateApiFetch<
    Schemas.ListingsResponseDto,
    AppControllerGetListingsError,
    undefined,
    {},
    AppControllerGetListingsQueryParams,
    {}
  >({ url: "/listings", method: "get", ...variables, signal });

/**
 * Returns paginated property listings with optional filters for search term, price range, property type, beds, and baths.
 */
export function appControllerGetListingsQuery(
  variables: AppControllerGetListingsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListingsResponseDto>;
};

export function appControllerGetListingsQuery(
  variables: AppControllerGetListingsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListingsResponseDto>)
    | reactQuery.SkipToken;
};

export function appControllerGetListingsQuery(
  variables: AppControllerGetListingsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/listings",
      operationId: "appControllerGetListings",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAppControllerGetListings(variables, signal),
  };
}

/**
 * Returns paginated property listings with optional filters for search term, price range, property type, beds, and baths.
 */
export const useSuspenseAppControllerGetListings = <
  TData = Schemas.ListingsResponseDto,
>(
  variables: AppControllerGetListingsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListingsResponseDto,
      AppControllerGetListingsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useRealEstateApiContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListingsResponseDto,
    AppControllerGetListingsError,
    TData
  >({
    ...appControllerGetListingsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Returns paginated property listings with optional filters for search term, price range, property type, beds, and baths.
 */
export const useAppControllerGetListings = <
  TData = Schemas.ListingsResponseDto,
>(
  variables: AppControllerGetListingsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListingsResponseDto,
      AppControllerGetListingsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useRealEstateApiContext(options);
  return reactQuery.useQuery<
    Schemas.ListingsResponseDto,
    AppControllerGetListingsError,
    TData
  >({
    ...appControllerGetListingsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type AppControllerGetListingByIdPathParams = {
  id: string;
};

export type AppControllerGetListingByIdQueryParams = {
  /**
   * Filter by admin status
   *
   * @example false
   */
  isAdmin?: boolean;
};

export type AppControllerGetListingByIdError = Fetcher.ErrorWrapper<undefined>;

export type AppControllerGetListingByIdVariables = {
  pathParams: AppControllerGetListingByIdPathParams;
  queryParams?: AppControllerGetListingByIdQueryParams;
} & RealEstateApiContext["fetcherOptions"];

/**
 * Returns a single property listing by its ID.
 */
export const fetchAppControllerGetListingById = (
  variables: AppControllerGetListingByIdVariables,
  signal?: AbortSignal,
) =>
  realEstateApiFetch<
    Schemas.ListingGetResponseDto,
    AppControllerGetListingByIdError,
    undefined,
    {},
    AppControllerGetListingByIdQueryParams,
    AppControllerGetListingByIdPathParams
  >({ url: "/listings/{id}", method: "get", ...variables, signal });

/**
 * Returns a single property listing by its ID.
 */
export function appControllerGetListingByIdQuery(
  variables: AppControllerGetListingByIdVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListingGetResponseDto>;
};

export function appControllerGetListingByIdQuery(
  variables: AppControllerGetListingByIdVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListingGetResponseDto>)
    | reactQuery.SkipToken;
};

export function appControllerGetListingByIdQuery(
  variables: AppControllerGetListingByIdVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/listings/{id}",
      operationId: "appControllerGetListingById",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAppControllerGetListingById(variables, signal),
  };
}

/**
 * Returns a single property listing by its ID.
 */
export const useSuspenseAppControllerGetListingById = <
  TData = Schemas.ListingGetResponseDto,
>(
  variables: AppControllerGetListingByIdVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListingGetResponseDto,
      AppControllerGetListingByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useRealEstateApiContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListingGetResponseDto,
    AppControllerGetListingByIdError,
    TData
  >({
    ...appControllerGetListingByIdQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

/**
 * Returns a single property listing by its ID.
 */
export const useAppControllerGetListingById = <
  TData = Schemas.ListingGetResponseDto,
>(
  variables: AppControllerGetListingByIdVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListingGetResponseDto,
      AppControllerGetListingByIdError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useRealEstateApiContext(options);
  return reactQuery.useQuery<
    Schemas.ListingGetResponseDto,
    AppControllerGetListingByIdError,
    TData
  >({
    ...appControllerGetListingByIdQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type QueryOperation =
  | {
      path: "/listings";
      operationId: "appControllerGetListings";
      variables: AppControllerGetListingsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/listings/{id}";
      operationId: "appControllerGetListingById";
      variables: AppControllerGetListingByIdVariables | reactQuery.SkipToken;
    };
